# Generated by Django 4.1.7 on 2023-02-25 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('cycle_number', models.IntegerField()),
                ('cycle_unit', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, default=None, max_length=100, null=True)),
                ('price_number', models.IntegerField(blank=True, default=None, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='items.item')),
            ],
        ),
    ]
