# Generated by Django 4.1.7 on 2023-02-25 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcategory',
            old_name='name',
            new_name='content_type',
        ),
    ]
