# Generated by Django 4.1.7 on 2023-02-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_taskcategory_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcategory',
            name='content_type',
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
